ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP7()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_1217 = (MDL_CLEDQIM*MDL_YDO*MDL_YTAU)/MDL_LAMBDASMEFT__EXP__2
      GC_1221 = (MDL_CLEDQRE*MDL_COMPLEXI*MDL_YDO*MDL_YTAU)
     $ /MDL_LAMBDASMEFT__EXP__2
      GC_1225 = -((MDL_CLEDQIM*MDL_YS*MDL_YTAU)
     $ /MDL_LAMBDASMEFT__EXP__2)
      GC_1226 = (MDL_CLEDQIM*MDL_YS*MDL_YTAU)/MDL_LAMBDASMEFT__EXP__2
      GC_1230 = (MDL_CLEDQRE*MDL_COMPLEXI*MDL_YS*MDL_YTAU)
     $ /MDL_LAMBDASMEFT__EXP__2
      GC_1288 = -((MDL_CTH*MDL_CUBIM*MDL_VEVHAT*MDL_YUP)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_1289 = (MDL_CTH*MDL_CUBRE*MDL_COMPLEXI*MDL_VEVHAT*MDL_YUP)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1296 = -((MDL_CTH*MDL_CUWIM*MDL_VEVHAT*MDL_YUP)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_1298 = (MDL_CTH*MDL_CUWRE*MDL_COMPLEXI*MDL_VEVHAT*MDL_YUP)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1309 = (MDL_CUBIM*MDL_STH*MDL_VEVHAT*MDL_YUP)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1310 = -((MDL_CUBRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YUP)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_1311 = -((MDL_CUWIM*MDL_STH*MDL_VEVHAT*MDL_YUP)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_1312 = (MDL_CUWRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YUP)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1355 = -((MDL_CLEQU1IM*MDL_YE*MDL_YUP)
     $ /MDL_LAMBDASMEFT__EXP__2)
      GC_1356 = (MDL_CLEQU1IM*MDL_YE*MDL_YUP)/MDL_LAMBDASMEFT__EXP__2
      GC_1360 = -((MDL_CLEQU1RE*MDL_COMPLEXI*MDL_YE*MDL_YUP)
     $ /MDL_LAMBDASMEFT__EXP__2)
      GC_1364 = -(MDL_CLEQU3IM*MDL_YE*MDL_YUP)/(2.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_1365 = -(MDL_CLEQU3IM*MDL_YE*MDL_YUP)/(4.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_1366 = (MDL_CLEQU3IM*MDL_YE*MDL_YUP)/(4.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_1367 = (MDL_CLEQU3IM*MDL_YE*MDL_YUP)/(2.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_1374 = -(MDL_CLEQU3RE*MDL_COMPLEXI*MDL_YE*MDL_YUP)/(4.000000D
     $ +00*MDL_LAMBDASMEFT__EXP__2)
      GC_1375 = (MDL_CLEQU3RE*MDL_COMPLEXI*MDL_YE*MDL_YUP)/(2.000000D
     $ +00*MDL_LAMBDASMEFT__EXP__2)
      GC_1382 = -((MDL_CLEQU1IM*MDL_YM*MDL_YUP)
     $ /MDL_LAMBDASMEFT__EXP__2)
      GC_1383 = (MDL_CLEQU1IM*MDL_YM*MDL_YUP)/MDL_LAMBDASMEFT__EXP__2
      GC_1387 = -((MDL_CLEQU1RE*MDL_COMPLEXI*MDL_YM*MDL_YUP)
     $ /MDL_LAMBDASMEFT__EXP__2)
      END
