C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(-2,-6,-5)*Gamma(-2,-4,-3)*Gamma(-1,2,-4)*Gamma(-1,4,-6)*Pro
C     jP(-5,3)*ProjP(-3,1)
C     
      SUBROUTINE FFFF21_3(F1, F2, F4, COUP, M3, W3,F3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 F3(6)
      COMPLEX*16 F4(*)
      REAL*8 M3
      REAL*8 P3(0:3)
      REAL*8 W3
      COMPLEX*16 DENOM
      F3(1) = +F1(1)+F2(1)+F4(1)
      F3(2) = +F1(2)+F2(2)+F4(2)
      P3(0) = -DBLE(F3(1))
      P3(1) = -DBLE(F3(2))
      P3(2) = -DIMAG(F3(2))
      P3(3) = -DIMAG(F3(1))
      DENOM = COUP/(P3(0)**2-P3(1)**2-P3(2)**2-P3(3)**2 - M3 * (M3 -CI
     $ * W3))
      F3(3)= DENOM*(-8D0 * CI)*(F1(5)*(F2(5)*F4(6)*(P3(1)+CI*(P3(2)))
     $ -F2(6)*F4(5)*(P3(1)+CI*(P3(2))))+F1(6)*(F2(5)*-F4(6)*(P3(0)
     $ +P3(3))+F2(6)*F4(5)*(P3(0)+P3(3))))
      F3(4)= DENOM*(-8D0 * CI)*(F1(5)*(F2(5)*F4(6)*(P3(0)-P3(3))+F2(6)
     $ *F4(5)*(-P3(0)+P3(3)))+F1(6)*(F2(5)*F4(6)*(-P3(1)+CI*(P3(2)))
     $ +F2(6)*F4(5)*(P3(1)-CI*(P3(2)))))
      F3(5)= DENOM*8D0 * CI * F1(6)*M3*(-F2(5)*F4(6)+F2(6)*F4(5))
      F3(6)= DENOM*8D0 * CI * F1(5)*M3*(F2(5)*F4(6)-F2(6)*F4(5))
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(-2,-6,-5)*Gamma(-2,-4,-3)*Gamma(-1,2,-4)*Gamma(-1,4,-6)*Pro
C     jP(-5,3)*ProjP(-3,1)
C     
      SUBROUTINE FFFF21_8_28_25_3(F1, F2, F4, COUP1, COUP2, COUP3,
     $  COUP4, M3, W3,F3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 F3(6)
      COMPLEX*16 F4(*)
      COMPLEX*16 FTMP(6)
      REAL*8 M3
      REAL*8 P3(0:3)
      REAL*8 W3
      COMPLEX*16 DENOM
      INTEGER*4 I
      CALL FFFF21_3(F1,F2,F4,COUP1,M3,W3,F3)
      CALL FFFF8_3(F1,F2,F4,COUP2,M3,W3,FTMP)
      DO I = 3, 6
        F3(I) = F3(I) + FTMP(I)
      ENDDO
      CALL FFFF28_3(F1,F2,F4,COUP3,M3,W3,FTMP)
      DO I = 3, 6
        F3(I) = F3(I) + FTMP(I)
      ENDDO
      CALL FFFF25_3(F1,F2,F4,COUP4,M3,W3,FTMP)
      DO I = 3, 6
        F3(I) = F3(I) + FTMP(I)
      ENDDO
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(-2,-6,-5)*Gamma(-2,-4,-3)*Gamma(-1,2,-4)*Gamma(-1,4,-6)*Pro
C     jP(-5,3)*ProjP(-3,1)
C     
      SUBROUTINE FFFF21_8_23_25_3(F1, F2, F4, COUP1, COUP2, COUP3,
     $  COUP4, M3, W3,F3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 F3(6)
      COMPLEX*16 F4(*)
      COMPLEX*16 FTMP(6)
      REAL*8 M3
      REAL*8 P3(0:3)
      REAL*8 W3
      COMPLEX*16 DENOM
      INTEGER*4 I
      CALL FFFF21_3(F1,F2,F4,COUP1,M3,W3,F3)
      CALL FFFF8_3(F1,F2,F4,COUP2,M3,W3,FTMP)
      DO I = 3, 6
        F3(I) = F3(I) + FTMP(I)
      ENDDO
      CALL FFFF23_3(F1,F2,F4,COUP3,M3,W3,FTMP)
      DO I = 3, 6
        F3(I) = F3(I) + FTMP(I)
      ENDDO
      CALL FFFF25_3(F1,F2,F4,COUP4,M3,W3,FTMP)
      DO I = 3, 6
        F3(I) = F3(I) + FTMP(I)
      ENDDO
      END


