version: 2
jobs:
   build:
     docker:
       - image: cmssw/cmssw:CMSSW_8_0_20
     steps:
       - run:
           name: cmsset_default
           command: |
             echo "source /opt/cms/cmsset_default.sh" >> $BASH_ENV
       - checkout
       - run:
           name: cmsrel
           command: scram p CMSSW CMSSW_8_0_20
           working_directory: $HOME
       - run:
           name: cmsenv
           command: |
             echo "cd $HOME/CMSSW_8_0_20 && eval $(scram ru -sh) && cd -" >> $BASH_ENV
       - run: echo "hello world"
       - run: pwd
       - run: ls
       - run: cd JHUGenMELAv2/MELA/ && ./setup.sh
