      subroutine wt2gen(q,wt2)
      implicit none
      include 'constants.f'
      include 'limits.f'
      include 'breit.f'
      include 'energy.f'
c----given a set of momenta generated calculate the weight 
c----which would have been assigned had it been generated by 
c----routine phase4      
      double precision q(mxpart,4),wt2,s3,ymax,dot
      double precision w3,wt0
      parameter(wt0=one/16d0/pi)
      s3=two*dot(q,6,7)
      ymax=log(sqrts/sqrt(s3))
      if (n3 .eq. 0) then
         w3=wsqmax-wsqmin
      elseif (n3 .eq. 1) then
        call breitw1(s3,wsqmin,wsqmax,mass3,width3,w3)       
      endif
      wt2=wt0*four*ymax*w3/sqrts**2
c      write(6,*) 'x1*x2=',s3/sqrts**2
c      pause
c      write(6,*) 'ymax',ymax
c      write(6,*) 'w3',w3
c      write(6,*) 'sqrts',sqrts
c      write(6,*) 'wt2',wt2
     
      return
      end






