ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP9()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_769 = (MDL_CLEDQRE*MDL_COMPLEXI*MDL_YDO*MDL_YE)
     $ /MDL_LAMBDASMEFT__EXP__2
      GC_773 = -((MDL_COMPLEXI*MDL_YM)/MDL_SQRT__2)
      GC_779 = -((MDL_CEBIM*MDL_CTH*MDL_YM)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2))
      GC_780 = (MDL_CEBRE*MDL_CTH*MDL_COMPLEXI*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_781 = (MDL_CEWIM*MDL_CTH*MDL_YM)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2)
      GC_782 = -((MDL_CEWRE*MDL_CTH*MDL_COMPLEXI*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_792 = (MDL_CEBIM*MDL_STH*MDL_YM)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2)
      GC_793 = -((MDL_CEBRE*MDL_COMPLEXI*MDL_STH*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_794 = (MDL_CEWIM*MDL_STH*MDL_YM)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2)
      GC_795 = -((MDL_CEWRE*MDL_COMPLEXI*MDL_STH*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_796 = (-3.000000D+00*MDL_CEHIM*MDL_VEVHAT*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_797 = (3.000000D+00*MDL_CEHRE*MDL_COMPLEXI*MDL_VEVHAT*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_801 = -((MDL_CEBIM*MDL_CTH*MDL_VEVHAT*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_802 = (MDL_CEBRE*MDL_CTH*MDL_COMPLEXI*MDL_VEVHAT*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_803 = (MDL_CEWIM*MDL_CTH*MDL_VEVHAT*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_804 = -((MDL_CEWRE*MDL_CTH*MDL_COMPLEXI*MDL_VEVHAT*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_813 = (MDL_CEBIM*MDL_STH*MDL_VEVHAT*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_814 = -((MDL_CEBRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_815 = (MDL_CEWIM*MDL_STH*MDL_VEVHAT*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_816 = -((MDL_CEWRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_817 = -((MDL_CEHIM*MDL_VEVHAT__EXP__2*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_818 = (MDL_CEHRE*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_819 = -((MDL_CHBOX*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_820 = (MDL_CHDD*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YM)
     $ /(4.000000D+00*MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_821 = (MDL_CHL3*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YM)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      END
