ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP5()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_505 = -((MDL_CDWRE*MDL_CTH*MDL_COMPLEXI*MDL_VEVHAT*MDL_YB)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_516 = (MDL_CDBIM*MDL_STH*MDL_VEVHAT*MDL_YB)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_517 = -((MDL_CDBRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YB)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_518 = (MDL_CDWIM*MDL_STH*MDL_VEVHAT*MDL_YB)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_519 = -((MDL_CDWRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YB)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_520 = -((MDL_CDHIM*MDL_VEVHAT__EXP__2*MDL_YB)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_521 = (MDL_CDHRE*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YB)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_522 = -((MDL_CHBOX*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YB)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_523 = (MDL_CHDD*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YB)
     $ /(4.000000D+00*MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_524 = (MDL_CHL3*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YB)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_525 = -(MDL_CLL1*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YB)
     $ /(2.000000D+00*MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_526 = -((MDL_COMPLEXI*MDL_YC)/MDL_SQRT__2)
      GC_527 = -((MDL_CTH*MDL_CUBIM*MDL_YC)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2))
      GC_528 = (MDL_CTH*MDL_CUBRE*MDL_COMPLEXI*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_535 = -((MDL_CTH*MDL_CUWIM*MDL_YC)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2))
      GC_537 = (MDL_CTH*MDL_CUWRE*MDL_COMPLEXI*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_549 = (MDL_CUBIM*MDL_STH*MDL_YC)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2)
      GC_550 = -((MDL_CUBRE*MDL_COMPLEXI*MDL_STH*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_551 = -((MDL_CUWIM*MDL_STH*MDL_YC)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2))
      GC_552 = (MDL_CUWRE*MDL_COMPLEXI*MDL_STH*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_553 = -((MDL_CTH*MDL_CUBIM*MDL_VEVHAT*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_554 = (MDL_CTH*MDL_CUBRE*MDL_COMPLEXI*MDL_VEVHAT*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_557 = (-3.000000D+00*MDL_CUHIM*MDL_VEVHAT*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_558 = (3.000000D+00*MDL_CUHRE*MDL_COMPLEXI*MDL_VEVHAT*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_561 = -((MDL_CTH*MDL_CUWIM*MDL_VEVHAT*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      END
