ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP7()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_833 = (MDL_CLEQU1IM*MDL_YC*MDL_YM)/MDL_LAMBDASMEFT__EXP__2
      GC_837 = -((MDL_CLEQU1RE*MDL_COMPLEXI*MDL_YC*MDL_YM)
     $ /MDL_LAMBDASMEFT__EXP__2)
      GC_841 = -(MDL_CLEQU3IM*MDL_YC*MDL_YM)/(2.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_842 = -(MDL_CLEQU3IM*MDL_YC*MDL_YM)/(4.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_843 = (MDL_CLEQU3IM*MDL_YC*MDL_YM)/(4.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_844 = (MDL_CLEQU3IM*MDL_YC*MDL_YM)/(2.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_851 = -(MDL_CLEQU3RE*MDL_COMPLEXI*MDL_YC*MDL_YM)/(4.000000D
     $ +00*MDL_LAMBDASMEFT__EXP__2)
      GC_852 = (MDL_CLEQU3RE*MDL_COMPLEXI*MDL_YC*MDL_YM)/(2.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_859 = -((MDL_CLEDQIM*MDL_YDO*MDL_YM)/MDL_LAMBDASMEFT__EXP__2)
      GC_860 = (MDL_CLEDQIM*MDL_YDO*MDL_YM)/MDL_LAMBDASMEFT__EXP__2
      GC_864 = (MDL_CLEDQRE*MDL_COMPLEXI*MDL_YDO*MDL_YM)
     $ /MDL_LAMBDASMEFT__EXP__2
      GC_868 = -((MDL_COMPLEXI*MDL_YS)/MDL_SQRT__2)
      GC_902 = -((MDL_CDBIM*MDL_CTH*MDL_VEVHAT*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_903 = (MDL_CDBRE*MDL_CTH*MDL_COMPLEXI*MDL_VEVHAT*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_904 = (MDL_CDWIM*MDL_CTH*MDL_VEVHAT*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_905 = -((MDL_CDWRE*MDL_CTH*MDL_COMPLEXI*MDL_VEVHAT*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_916 = (MDL_CDBIM*MDL_STH*MDL_VEVHAT*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_917 = -((MDL_CDBRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_918 = (MDL_CDWIM*MDL_STH*MDL_VEVHAT*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_919 = -((MDL_CDWRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_920 = -((MDL_CDHIM*MDL_VEVHAT__EXP__2*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_921 = (MDL_CDHRE*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_922 = -((MDL_CHBOX*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_923 = (MDL_CHDD*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YS)
     $ /(4.000000D+00*MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_924 = (MDL_CHL3*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      END
