ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP8()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_709 = -((MDL_CEWRE*MDL_CTH*MDL_COMPLEXI*MDL_VEVHAT*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_718 = (MDL_CEBIM*MDL_STH*MDL_VEVHAT*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_719 = -((MDL_CEBRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_720 = (MDL_CEWIM*MDL_STH*MDL_VEVHAT*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_721 = -((MDL_CEWRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_722 = -((MDL_CEHIM*MDL_VEVHAT__EXP__2*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_723 = (MDL_CEHRE*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_724 = -((MDL_CHBOX*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_725 = (MDL_CHDD*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YE)
     $ /(4.000000D+00*MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_726 = (MDL_CHL3*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YE)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_727 = -(MDL_CLL1*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YE)
     $ /(2.000000D+00*MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_728 = -((MDL_CLEDQIM*MDL_YB*MDL_YE)/MDL_LAMBDASMEFT__EXP__2)
      GC_729 = (MDL_CLEDQIM*MDL_YB*MDL_YE)/MDL_LAMBDASMEFT__EXP__2
      GC_733 = (MDL_CLEDQRE*MDL_COMPLEXI*MDL_YB*MDL_YE)
     $ /MDL_LAMBDASMEFT__EXP__2
      GC_737 = -((MDL_CLEQU1IM*MDL_YC*MDL_YE)/MDL_LAMBDASMEFT__EXP__2)
      GC_738 = (MDL_CLEQU1IM*MDL_YC*MDL_YE)/MDL_LAMBDASMEFT__EXP__2
      GC_742 = -((MDL_CLEQU1RE*MDL_COMPLEXI*MDL_YC*MDL_YE)
     $ /MDL_LAMBDASMEFT__EXP__2)
      GC_746 = -(MDL_CLEQU3IM*MDL_YC*MDL_YE)/(2.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_747 = -(MDL_CLEQU3IM*MDL_YC*MDL_YE)/(4.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_748 = (MDL_CLEQU3IM*MDL_YC*MDL_YE)/(4.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_749 = (MDL_CLEQU3IM*MDL_YC*MDL_YE)/(2.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_756 = -(MDL_CLEQU3RE*MDL_COMPLEXI*MDL_YC*MDL_YE)/(4.000000D
     $ +00*MDL_LAMBDASMEFT__EXP__2)
      GC_757 = (MDL_CLEQU3RE*MDL_COMPLEXI*MDL_YC*MDL_YE)/(2.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_764 = -((MDL_CLEDQIM*MDL_YDO*MDL_YE)/MDL_LAMBDASMEFT__EXP__2)
      GC_765 = (MDL_CLEDQIM*MDL_YDO*MDL_YE)/MDL_LAMBDASMEFT__EXP__2
      END
