ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP12()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_1138 = (MDL_CEWIM*MDL_CTH*MDL_YTAU)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2)
      GC_1139 = -((MDL_CEWRE*MDL_CTH*MDL_COMPLEXI*MDL_YTAU)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_1149 = (MDL_CEBIM*MDL_STH*MDL_YTAU)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2)
      GC_1150 = -((MDL_CEBRE*MDL_COMPLEXI*MDL_STH*MDL_YTAU)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_1151 = (MDL_CEWIM*MDL_STH*MDL_YTAU)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2)
      GC_1152 = -((MDL_CEWRE*MDL_COMPLEXI*MDL_STH*MDL_YTAU)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_1153 = (-3.000000D+00*MDL_CEHIM*MDL_VEVHAT*MDL_YTAU)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1154 = (3.000000D+00*MDL_CEHRE*MDL_COMPLEXI*MDL_VEVHAT
     $ *MDL_YTAU)/(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1158 = -((MDL_CEBIM*MDL_CTH*MDL_VEVHAT*MDL_YTAU)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_1159 = (MDL_CEBRE*MDL_CTH*MDL_COMPLEXI*MDL_VEVHAT*MDL_YTAU)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1160 = (MDL_CEWIM*MDL_CTH*MDL_VEVHAT*MDL_YTAU)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1161 = -((MDL_CEWRE*MDL_CTH*MDL_COMPLEXI*MDL_VEVHAT*MDL_YTAU)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_1170 = (MDL_CEBIM*MDL_STH*MDL_VEVHAT*MDL_YTAU)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1171 = -((MDL_CEBRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YTAU)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_1172 = (MDL_CEWIM*MDL_STH*MDL_VEVHAT*MDL_YTAU)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1173 = -((MDL_CEWRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YTAU)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_1174 = -((MDL_CEHIM*MDL_VEVHAT__EXP__2*MDL_YTAU)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_1175 = (MDL_CEHRE*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YTAU)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1176 = -((MDL_CHBOX*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YTAU)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_1177 = (MDL_CHDD*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YTAU)
     $ /(4.000000D+00*MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1178 = (MDL_CHL3*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YTAU)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1179 = -(MDL_CLL1*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YTAU)
     $ /(2.000000D+00*MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1180 = -((MDL_CLEDQIM*MDL_YB*MDL_YTAU)
     $ /MDL_LAMBDASMEFT__EXP__2)
      GC_1181 = (MDL_CLEDQIM*MDL_YB*MDL_YTAU)/MDL_LAMBDASMEFT__EXP__2
      GC_1185 = (MDL_CLEDQRE*MDL_COMPLEXI*MDL_YB*MDL_YTAU)
     $ /MDL_LAMBDASMEFT__EXP__2
      END
