ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP8()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_925 = -(MDL_CLL1*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YS)
     $ /(2.000000D+00*MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_944 = -((MDL_CLEDQIM*MDL_YE*MDL_YS)/MDL_LAMBDASMEFT__EXP__2)
      GC_945 = (MDL_CLEDQIM*MDL_YE*MDL_YS)/MDL_LAMBDASMEFT__EXP__2
      GC_949 = (MDL_CLEDQRE*MDL_COMPLEXI*MDL_YE*MDL_YS)
     $ /MDL_LAMBDASMEFT__EXP__2
      GC_953 = -((MDL_CLEDQIM*MDL_YM*MDL_YS)/MDL_LAMBDASMEFT__EXP__2)
      GC_954 = (MDL_CLEDQIM*MDL_YM*MDL_YS)/MDL_LAMBDASMEFT__EXP__2
      GC_958 = (MDL_CLEDQRE*MDL_COMPLEXI*MDL_YM*MDL_YS)
     $ /MDL_LAMBDASMEFT__EXP__2
      GC_1158 = -((MDL_CEBIM*MDL_CTH*MDL_VEVHAT*MDL_YTAU)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_1159 = (MDL_CEBRE*MDL_CTH*MDL_COMPLEXI*MDL_VEVHAT*MDL_YTAU)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1160 = (MDL_CEWIM*MDL_CTH*MDL_VEVHAT*MDL_YTAU)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1161 = -((MDL_CEWRE*MDL_CTH*MDL_COMPLEXI*MDL_VEVHAT*MDL_YTAU)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_1170 = (MDL_CEBIM*MDL_STH*MDL_VEVHAT*MDL_YTAU)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1171 = -((MDL_CEBRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YTAU)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_1172 = (MDL_CEWIM*MDL_STH*MDL_VEVHAT*MDL_YTAU)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_1173 = -((MDL_CEWRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YTAU)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_1180 = -((MDL_CLEDQIM*MDL_YB*MDL_YTAU)
     $ /MDL_LAMBDASMEFT__EXP__2)
      GC_1181 = (MDL_CLEDQIM*MDL_YB*MDL_YTAU)/MDL_LAMBDASMEFT__EXP__2
      GC_1185 = (MDL_CLEDQRE*MDL_COMPLEXI*MDL_YB*MDL_YTAU)
     $ /MDL_LAMBDASMEFT__EXP__2
      GC_1189 = -((MDL_CLEQU1IM*MDL_YC*MDL_YTAU)
     $ /MDL_LAMBDASMEFT__EXP__2)
      GC_1190 = (MDL_CLEQU1IM*MDL_YC*MDL_YTAU)/MDL_LAMBDASMEFT__EXP__2
      GC_1194 = -((MDL_CLEQU1RE*MDL_COMPLEXI*MDL_YC*MDL_YTAU)
     $ /MDL_LAMBDASMEFT__EXP__2)
      GC_1198 = -(MDL_CLEQU3IM*MDL_YC*MDL_YTAU)/(2.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_1199 = -(MDL_CLEQU3IM*MDL_YC*MDL_YTAU)/(4.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_1200 = (MDL_CLEQU3IM*MDL_YC*MDL_YTAU)/(4.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_1201 = (MDL_CLEQU3IM*MDL_YC*MDL_YTAU)/(2.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      END
