ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP10()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_822 = -(MDL_CLL1*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YM)
     $ /(2.000000D+00*MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_823 = -((MDL_CLEDQIM*MDL_YB*MDL_YM)/MDL_LAMBDASMEFT__EXP__2)
      GC_824 = (MDL_CLEDQIM*MDL_YB*MDL_YM)/MDL_LAMBDASMEFT__EXP__2
      GC_828 = (MDL_CLEDQRE*MDL_COMPLEXI*MDL_YB*MDL_YM)
     $ /MDL_LAMBDASMEFT__EXP__2
      GC_832 = -((MDL_CLEQU1IM*MDL_YC*MDL_YM)/MDL_LAMBDASMEFT__EXP__2)
      GC_833 = (MDL_CLEQU1IM*MDL_YC*MDL_YM)/MDL_LAMBDASMEFT__EXP__2
      GC_837 = -((MDL_CLEQU1RE*MDL_COMPLEXI*MDL_YC*MDL_YM)
     $ /MDL_LAMBDASMEFT__EXP__2)
      GC_841 = -(MDL_CLEQU3IM*MDL_YC*MDL_YM)/(2.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_842 = -(MDL_CLEQU3IM*MDL_YC*MDL_YM)/(4.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_843 = (MDL_CLEQU3IM*MDL_YC*MDL_YM)/(4.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_844 = (MDL_CLEQU3IM*MDL_YC*MDL_YM)/(2.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_851 = -(MDL_CLEQU3RE*MDL_COMPLEXI*MDL_YC*MDL_YM)/(4.000000D
     $ +00*MDL_LAMBDASMEFT__EXP__2)
      GC_852 = (MDL_CLEQU3RE*MDL_COMPLEXI*MDL_YC*MDL_YM)/(2.000000D+00
     $ *MDL_LAMBDASMEFT__EXP__2)
      GC_859 = -((MDL_CLEDQIM*MDL_YDO*MDL_YM)/MDL_LAMBDASMEFT__EXP__2)
      GC_860 = (MDL_CLEDQIM*MDL_YDO*MDL_YM)/MDL_LAMBDASMEFT__EXP__2
      GC_864 = (MDL_CLEDQRE*MDL_COMPLEXI*MDL_YDO*MDL_YM)
     $ /MDL_LAMBDASMEFT__EXP__2
      GC_868 = -((MDL_COMPLEXI*MDL_YS)/MDL_SQRT__2)
      GC_876 = -((MDL_CDBIM*MDL_CTH*MDL_YS)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2))
      GC_877 = (MDL_CDBRE*MDL_CTH*MDL_COMPLEXI*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_878 = (MDL_CDWIM*MDL_CTH*MDL_YS)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2)
      GC_879 = -((MDL_CDWRE*MDL_CTH*MDL_COMPLEXI*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_891 = (MDL_CDBIM*MDL_STH*MDL_YS)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2)
      GC_892 = -((MDL_CDBRE*MDL_COMPLEXI*MDL_STH*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_893 = (MDL_CDWIM*MDL_STH*MDL_YS)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2)
      GC_894 = -((MDL_CDWRE*MDL_COMPLEXI*MDL_STH*MDL_YS)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      END
