ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMEFTsim_U35_alphaScheme_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_225 = ', GC_225
      WRITE(*,2) 'GC_229 = ', GC_229
      WRITE(*,2) 'GC_234 = ', GC_234
      WRITE(*,2) 'GC_238 = ', GC_238
      WRITE(*,2) 'GC_4 = ', GC_4
      WRITE(*,2) 'GC_136 = ', GC_136
      WRITE(*,2) 'GC_197 = ', GC_197
      WRITE(*,2) 'GC_269 = ', GC_269
      WRITE(*,2) 'GC_270 = ', GC_270
      WRITE(*,2) 'GC_271 = ', GC_271
      WRITE(*,2) 'GC_272 = ', GC_272
      WRITE(*,2) 'GC_285 = ', GC_285
      WRITE(*,2) 'GC_319 = ', GC_319
      WRITE(*,2) 'GC_320 = ', GC_320
      WRITE(*,2) 'GC_321 = ', GC_321
      WRITE(*,2) 'GC_322 = ', GC_322
      WRITE(*,2) 'GC_323 = ', GC_323
      WRITE(*,2) 'GC_324 = ', GC_324
      WRITE(*,2) 'GC_325 = ', GC_325
      WRITE(*,2) 'GC_326 = ', GC_326
      WRITE(*,2) 'GC_327 = ', GC_327
      WRITE(*,2) 'GC_328 = ', GC_328
      WRITE(*,2) 'GC_329 = ', GC_329
      WRITE(*,2) 'GC_330 = ', GC_330
      WRITE(*,2) 'GC_352 = ', GC_352
      WRITE(*,2) 'GC_353 = ', GC_353
      WRITE(*,2) 'GC_364 = ', GC_364
      WRITE(*,2) 'GC_384 = ', GC_384
      WRITE(*,2) 'GC_387 = ', GC_387
      WRITE(*,2) 'GC_392 = ', GC_392
      WRITE(*,2) 'GC_395 = ', GC_395
      WRITE(*,2) 'GC_398 = ', GC_398
      WRITE(*,2) 'GC_435 = ', GC_435
      WRITE(*,2) 'GC_436 = ', GC_436
      WRITE(*,2) 'GC_437 = ', GC_437
      WRITE(*,2) 'GC_438 = ', GC_438
      WRITE(*,2) 'GC_464 = ', GC_464
      WRITE(*,2) 'GC_465 = ', GC_465
      WRITE(*,2) 'GC_466 = ', GC_466
      WRITE(*,2) 'GC_467 = ', GC_467
      WRITE(*,2) 'GC_708 = ', GC_708
      WRITE(*,2) 'GC_709 = ', GC_709
      WRITE(*,2) 'GC_718 = ', GC_718
      WRITE(*,2) 'GC_719 = ', GC_719
      WRITE(*,2) 'GC_803 = ', GC_803
      WRITE(*,2) 'GC_804 = ', GC_804
      WRITE(*,2) 'GC_813 = ', GC_813
      WRITE(*,2) 'GC_814 = ', GC_814
