ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP6()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_563 = (MDL_CTH*MDL_CUWRE*MDL_COMPLEXI*MDL_VEVHAT*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_574 = (MDL_CUBIM*MDL_STH*MDL_VEVHAT*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_575 = -((MDL_CUBRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_576 = -((MDL_CUWIM*MDL_STH*MDL_VEVHAT*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_577 = (MDL_CUWRE*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_578 = -((MDL_CHBOX*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_579 = (MDL_CHDD*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YC)
     $ /(4.000000D+00*MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_580 = (MDL_CHL3*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_581 = -(MDL_CLL1*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YC)
     $ /(2.000000D+00*MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_582 = -((MDL_CUHIM*MDL_VEVHAT__EXP__2*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_583 = (MDL_CUHRE*MDL_COMPLEXI*MDL_VEVHAT__EXP__2*MDL_YC)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_602 = -((MDL_COMPLEXI*MDL_YDO)/MDL_SQRT__2)
      GC_610 = -((MDL_CDBIM*MDL_CTH*MDL_YDO)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2))
      GC_611 = (MDL_CDBRE*MDL_CTH*MDL_COMPLEXI*MDL_YDO)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_612 = (MDL_CDWIM*MDL_CTH*MDL_YDO)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2)
      GC_613 = -((MDL_CDWRE*MDL_CTH*MDL_COMPLEXI*MDL_YDO)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_625 = (MDL_CDBIM*MDL_STH*MDL_YDO)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2)
      GC_626 = -((MDL_CDBRE*MDL_COMPLEXI*MDL_STH*MDL_YDO)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_627 = (MDL_CDWIM*MDL_STH*MDL_YDO)/(MDL_LAMBDASMEFT__EXP__2
     $ *MDL_SQRT__2)
      GC_628 = -((MDL_CDWRE*MDL_COMPLEXI*MDL_STH*MDL_YDO)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_631 = (-3.000000D+00*MDL_CDHIM*MDL_VEVHAT*MDL_YDO)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_632 = (3.000000D+00*MDL_CDHRE*MDL_COMPLEXI*MDL_VEVHAT*MDL_YDO)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_636 = -((MDL_CDBIM*MDL_CTH*MDL_VEVHAT*MDL_YDO)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_637 = (MDL_CDBRE*MDL_CTH*MDL_COMPLEXI*MDL_VEVHAT*MDL_YDO)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_638 = (MDL_CDWIM*MDL_CTH*MDL_VEVHAT*MDL_YDO)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      END
