ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP2()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_271 = (4.000000D+00*MDL_CHW*MDL_CTH__EXP__2*MDL_COMPLEXI
     $ *MDL_VEVHAT)/MDL_LAMBDASMEFT__EXP__2
      GC_272 = (-2.000000D+00*MDL_CHWTIL*MDL_CTH__EXP__2*MDL_COMPLEXI
     $ *MDL_VEVHAT)/MDL_LAMBDASMEFT__EXP__2
      GC_285 = (MDL_EE__EXP__2*MDL_COMPLEXI*MDL_VEVHAT)/(2.000000D+00
     $ *MDL_CTH__EXP__2*MDL_STH__EXP__2)
      GC_305 = (MDL_CHD*MDL_EE*MDL_COMPLEXI*MDL_VEVHAT)/(MDL_CTH
     $ *MDL_LAMBDASMEFT__EXP__2*MDL_STH)
      GC_306 = (MDL_CHE*MDL_EE*MDL_COMPLEXI*MDL_VEVHAT)/(MDL_CTH
     $ *MDL_LAMBDASMEFT__EXP__2*MDL_STH)
      GC_307 = (MDL_CHL1*MDL_EE*MDL_COMPLEXI*MDL_VEVHAT)/(MDL_CTH
     $ *MDL_LAMBDASMEFT__EXP__2*MDL_STH)
      GC_309 = (MDL_CHL3*MDL_EE*MDL_COMPLEXI*MDL_VEVHAT)/(MDL_CTH
     $ *MDL_LAMBDASMEFT__EXP__2*MDL_STH)
      GC_310 = (MDL_CHQ1*MDL_EE*MDL_COMPLEXI*MDL_VEVHAT)/(MDL_CTH
     $ *MDL_LAMBDASMEFT__EXP__2*MDL_STH)
      GC_311 = -((MDL_CHQ3*MDL_EE*MDL_COMPLEXI*MDL_VEVHAT)/(MDL_CTH
     $ *MDL_LAMBDASMEFT__EXP__2*MDL_STH))
      GC_312 = (MDL_CHQ3*MDL_EE*MDL_COMPLEXI*MDL_VEVHAT)/(MDL_CTH
     $ *MDL_LAMBDASMEFT__EXP__2*MDL_STH)
      GC_313 = (MDL_CHU*MDL_EE*MDL_COMPLEXI*MDL_VEVHAT)/(MDL_CTH
     $ *MDL_LAMBDASMEFT__EXP__2*MDL_STH)
      GC_319 = (-4.000000D+00*MDL_CHB*MDL_CTH*MDL_COMPLEXI*MDL_STH
     $ *MDL_VEVHAT)/MDL_LAMBDASMEFT__EXP__2
      GC_320 = (-4.000000D+00*MDL_CHBTIL*MDL_CTH*MDL_COMPLEXI*MDL_STH
     $ *MDL_VEVHAT)/MDL_LAMBDASMEFT__EXP__2
      GC_321 = (4.000000D+00*MDL_CHW*MDL_CTH*MDL_COMPLEXI*MDL_STH
     $ *MDL_VEVHAT)/MDL_LAMBDASMEFT__EXP__2
      GC_322 = (-4.000000D+00*MDL_CHWB*MDL_CTH*MDL_COMPLEXI*MDL_STH
     $ *MDL_VEVHAT)/MDL_LAMBDASMEFT__EXP__2
      GC_323 = (4.000000D+00*MDL_CHWB*MDL_CTH*MDL_COMPLEXI*MDL_STH
     $ *MDL_VEVHAT)/MDL_LAMBDASMEFT__EXP__2
      GC_324 = (-2.000000D+00*MDL_CHWBTIL*MDL_CTH*MDL_COMPLEXI*MDL_STH
     $ *MDL_VEVHAT)/MDL_LAMBDASMEFT__EXP__2
      GC_325 = (2.000000D+00*MDL_CHWBTIL*MDL_CTH*MDL_COMPLEXI*MDL_STH
     $ *MDL_VEVHAT)/MDL_LAMBDASMEFT__EXP__2
      GC_326 = (4.000000D+00*MDL_CHWTIL*MDL_CTH*MDL_COMPLEXI*MDL_STH
     $ *MDL_VEVHAT)/MDL_LAMBDASMEFT__EXP__2
      GC_327 = (4.000000D+00*MDL_CHB*MDL_COMPLEXI*MDL_STH__EXP__2
     $ *MDL_VEVHAT)/MDL_LAMBDASMEFT__EXP__2
      GC_328 = (-2.000000D+00*MDL_CHBTIL*MDL_COMPLEXI*MDL_STH__EXP__2
     $ *MDL_VEVHAT)/MDL_LAMBDASMEFT__EXP__2
      GC_329 = (4.000000D+00*MDL_CHW*MDL_COMPLEXI*MDL_STH__EXP__2
     $ *MDL_VEVHAT)/MDL_LAMBDASMEFT__EXP__2
      GC_330 = (-2.000000D+00*MDL_CHWTIL*MDL_COMPLEXI*MDL_STH__EXP__2
     $ *MDL_VEVHAT)/MDL_LAMBDASMEFT__EXP__2
      GC_350 = (MDL_CHD*MDL_EE*MDL_COMPLEXI*MDL_VEVHAT__EXP__2)
     $ /(2.000000D+00*MDL_CTH*MDL_LAMBDASMEFT__EXP__2*MDL_STH)
      GC_352 = (MDL_CHE*MDL_EE*MDL_COMPLEXI*MDL_VEVHAT__EXP__2)
     $ /(2.000000D+00*MDL_CTH*MDL_LAMBDASMEFT__EXP__2*MDL_STH)
      END
