#############################################################################
#      written by the UFO converter
#############################################################################

MODEL = couplings.o lha_read.o printout.o rw_para.o model_functions.o couplings1.o couplings2.o couplings3.o couplings4.o couplings5.o couplings6.o couplings7.o couplings8.o couplings9.o couplings10.o couplings11.o couplings12.o couplings13.o couplings14.o couplings15.o couplings16.o